### ISSUE TITLE
User Interface - Feedback

### ISSUE THREAD

**Issue by darkhobbo** [Huzzari/myTruApp#4]
Interface buttons need better user feedback, currently on press the buttons do not notify the user of a registered press.

Perhaps changing button color etc.

**Comment by Huzzari** [comment]
Added audio feedback to button clicks.

**Comment by Huzzari** [comment]
both audio feedback and button colour change are implemented. Colour can be changed by altering the string "backgroundColour" at the top of each page. the sound can be altered by simply changing out the mp3 file in the folder "raw" in the "res" folder. make sure to keep the same name for the audio file.
